### ISSUE TITLE
Format for the /opt/hide.me/config

### ISSUE THREAD

**Issue by bslavin** [eventure/hide.client.linux#12]
I am trying to use systemctl and pass the `-s 192.168.1.0/24` network 

my config file is:

OPTIONS=-s 192.168.1.0/24

but each time I  restart I lose the ability to ping local machines. 

I have tried
OPTIONS="-s 192.168.1.0/24"
OPTIONS=`-s 192.168.1.0/24`
OPTIONS=-'s 192.168.1.0/24'
OPTIONS=s 192.168.1.0/24

Any help on the syntax would be appreciated.

**Comment by tcohar** [comment]
Hi,

the following format should work, I tested it again:

`OPTIONS=-s 192.168.1.0/24`
